### ISSUE TITLE
Slide content disapears when resize screen 

### ISSUE THREAD

**Issue by diego-j-gonzalez** [vitalii-andriiovskyi/ngx-owl-carousel-o#21] opened 2019-02-20 11:52 UTC
The content of each item disapears when resize screen with this config: 

`carouselOpt: any = {
    loop: true,
    mouseDrag: false,
    touchDrag: false,
    pullDrag: false,
    dots: false,
    navSpeed: 700,
    navText: ['<img src="/assets/images/icons/angle-left.svg">', '<img src="/assets/images/icons/angle-right.svg">'],
    slideBy: 2,
    responsive: {
      0: {
        items: 1
      },
      400: {
        items: 2
      },
      740: {
        items: 4
      },
      960: {
        items: 5
      }
    },
    nav: true
  };`

`<owl-carousel-o [options]="carouselOpt">
        <ng-template carouselSlide [id]="item.ID" *ngFor="let item of items">
          <div class="item-card-grid">
            <div class="item-img">
                <a routerLink="/item/{{ item.URL }}"><img src="{{ itemImg + item.ID_IMG }}.jpg" ></a>
            </div>
            <div class="look-content">
              <a class="name" routerLink="/item/{{ item.URL }}">{{ item.NAME }}</a>
            </div>
          </div>
        </ng-template>
      </owl-carousel-o>`

**Comment by vitalii-andriiovskyi** [comment] 2019-02-22 10:59
Hi. I think the problem is with `id` of the slide `"item.ID"`. It could be `undefined`. 
The internal code of the library uses the `id` for updating the prop `load` of `SlideModel` in the case of firing the event `resize`. If `id` is `false` or `undefined`, `load` becomes `false` and slide content gets invisible. By default `id` always has value, so `load` is always `true`.

To see id of the slide you can do:
- declare template reference variable `#owlCar`:
```html
 <owl-carousel-o [options]="customOptions" #owlCar>
```

- then in the component: 
```typescript
export class HomeComponent implements OnInit, AfterViewChecked {
  @ViewChild('owlCar') carouselEl: CarouselComponent;
  ngAfterViewChecked() {
    console.log(this.carouselEl.slidesData);
  }
}
```

Note: there'll be `ids` `cloned-1` ... `cloned-n`. Such ids shouldn't be taken into account into your code because the part `cloned-` will be skipped while exposing data about slides to any part of your code outside of the carousel.

**Comment by uitcode** [comment] 2019-02-24 12:16
I have the same problem when changing the screen size, looking forward to getting help from you!

**Comment by vitalii-andriiovskyi** [comment] 2019-02-24 13:05
@uitcode, 
check, please, ids of slides. Do they have values needed for your case or are their values `undefined`? 

You can see ids following the example described in the comment above or using any event of the library. However, in the second case, you will see just data about active slides.

**Comment by rankitbishnoi** [comment] 2019-04-09 11:15
@vitalii-andriiovskyi I am having the same issue. I have also logged the ids and they are not undefined.

**Comment by vitalii-andriiovskyi** [comment] 2019-04-09 11:47
@rankitbishnoi,
Are your ids strings or numbers. They should be passed into carousel as strings.

**Comment by smaillns** [comment] 2019-12-03 21:45
I think that you can close the issue! the problem was surely with the Id

**Closed** 2019-12-06 17:46 UTC

**Comment by Agranom** [comment] 2020-08-12 10:52
I'm having the same issue. Id is string, but component inside ng-template is destroyed and re-inited while resizing the page
