### ISSUE TITLE
xgx-owl-carousel-0 did not work with mat-tab angular 8

### ISSUE THREAD

**Issue by SouengKimmeng** [vitalii-andriiovskyi/ngx-owl-carousel-o#47] opened 2019-10-25 04:13 UTC
Hello everyone,

Could you help to check it that. it did not work when I add that owl-carousel inside mat-tab-group and  mat-tab.

Thank

**Comment by vitalii-andriiovskyi** [comment] 2019-10-26 21:15
Hi @SouengKimmeng.

Please supply the details of your problem so I could reproduce your issue. Show what do you see in the console.

**Comment by itsmeui** [comment] 2019-10-28 18:56
I am also facing an issue in the Angular 8 application. I am using the material tab and inside calling the ngx-owl-carousel but the carousel is not loading initially but if I resize the page then the carousel is loading. You can find the code from https://github.com/itsmeui/tabissue.

Please help me.

**Comment by SouengKimmeng** [comment] 2019-10-29 05:18
Hello @vitalii-andriiovskyi  yes pls check code that @itsmeui  meet. my problems same as @itsmeui . Thank you so much for your respond

**Comment by vitalii-andriiovskyi** [comment] 2019-10-29 18:26
Hi @SouengKimmeng , @itsmeui 

The core of the problem is that the carousel gets rendered too early. When the carousel starts rendering the `.mat-tab-body-content` has the width of `0px`. The carousel assigns this width to the width of `div.owl-carousel` and then the `div.owl-stage`.  At the end all slides have the same width. 

When the `resize` event fires the carousel recalculates all widths again. This is why you could be able to see images later. 
So the task is to render the carousel a little bit later. 

Possible solution is: 
`app.component.ts`:
```typescript
export class AppComponent implements AfterViewChecked {
  customOptions: OwlOptions = {
    loop: true,
    mouseDrag: false,
    touchDrag: false,
    pullDrag: false,
    dots: false,
    navSpeed: 700,
    navText: ['', ''],
    responsive: {
      0: {
        items: 1
      },
      400: {
        items: 2
      },
      740: {
        items: 4
      },
      940: {
        items: 3
      }
    },
    nav: true
  };
  

  @ViewChild('carouselHolder', { static: false }) carouselHolder: ElementRef;
  isCarouselFor1stTabVisible = false;

  ngAfterViewChecked() {
    this.showCarousel();
  }

  showCarousel(): void {
    if (this.carouselHolder.nativeElement.clientWidth > 0 && !this.isCarouselFor1stTabVisible) {
      setTimeout(() => {
        // console.log(this.carouselHolder.nativeElement);
        this.isCarouselFor1stTabVisible =  true;
      }, 0);
    }
  }
}
```

`app.component.html`:
```html
<mat-tab label="First"> 
    <div style="min-height: 1px;" #carouselHolder>
    
      <ng-container *ngIf="isCarouselFor1stTabVisible">

        <owl-carousel-o [options]="customOptions">
          <ng-template carouselSlide><img src="../assets/images/bag.png" alt=""></ng-template>  
          <ng-template carouselSlide><img src="../assets/images/banner-image.png" alt=""></ng-template>  
          <ng-template carouselSlide><img src="../assets/images/counseller.png" alt=""></ng-template>  
          <ng-template carouselSlide><img src="../assets/images/counseller.png" alt=""></ng-template>  
          <ng-template carouselSlide><img src="../assets/images/bag.png" alt=""></ng-template>  
          <ng-template carouselSlide><img src="../assets/images/banner-image.png" alt=""></ng-template>  
          <ng-template carouselSlide><img src="../assets/images/counseller.png" alt=""></ng-template>  
          <ng-template carouselSlide><img src="../assets/images/counseller.png" alt=""></ng-template>  
        </owl-carousel-o>
      </ng-container> 
    </div>

  </mat-tab>

```

**Comment by itsmeui** [comment] 2019-10-29 18:36
@vitalii-andriiovskyi thank you so much for your solution, the issue is fixed now.

**Comment by SouengKimmeng** [comment] 2019-10-30 03:15
@vitalii-andriiovskyi  thank you o much for support now it work fine.

**Closed** 2019-11-07 14:36 UTC

**Comment by sumitmangela** [comment] 2020-04-17 03:26
in angular material if you follow this syntax for the mat tab then the tab will be lazy loaded. hence the owl carousel will be loaded properly

```<mat-tab-group>
<mat-tab label="First">
    <ng-template matTabContent>
      owl carousel
    </ng-template>
  </mat-tab>
</mat-tab-group>

**Comment by PauChan19** [comment] 2022-04-29 15:46
Hi, guys, i need your help about this theme: if i use (this.carouselHolder.nativeElement.clientWidth > 0 && !this.isCarouselFor1stTabVisible) 
in console it´s show  "undefined" and  i don´t understand why. 

in the html the code is:
<mat-tab-group>
              <mat-tab label="Vistos recientemente">
                <div  #carouselHolder>
                    <ng-container *ngIf="isCarouselFor1stTabVisible">
                        <ng-container  *ngIf="dataViews">
                            <owl-carousel-o [options]="customOptions">
                                <ng-template carouselSlide *ngFor="let inscription of filtroC">
                                    <div class="slide courseCard"> <a [routerLink]="'/cursos/view/' + inscription.courseId" title="Ir al curso {{info.titulo}}" >
                                            <span [ngStyle]="{'background-color': inscription.course.sector.colorTheme}">
                                                <img class="imgCarrusel" [src]="inscription.course.imageUrl" alt="icon"> <br> 
                                                
                                            </span>  
                                        </a>
                                        <div>
                                            <span class="course text-center"><strong [ngStyle]="{'color': inscription.course.sector.colorTheme}">{{inscription.course.name}}</strong></span> <br>
                                            <span class="date"><strong>{{  inscription.lastUpdate | date:'shortDate' }}</strong></span>
                                        </div>
                                    </div> 
                                </ng-template>
                            </owl-carousel-o>
                        </ng-container>
                    </ng-container>
                </div>
               
              </mat-tab>
-------
in the .ts is:
@ViewChild('carouselHolder', { static: false}) carouselHolder: ElementRef;
  
  @ViewChild('carouselHolder2', { static: false }) carouselHolder2: ElementRef;
  isCarouselFor1stTabVisible = false;
  isCarouselFor1stTabVisible2 = false;

  ngAfterViewChecked(): void {
    this.showCarousel1();
    this.showCarousel2();
  }

  showCarousel1(): void {
    if (this.carouselHolder.nativeElement.clientWidth > 0 && !this.isCarouselFor1stTabVisible) {
      setTimeout(() => {
        console.log(this.carouselHolder.nativeElement.value);
        this.isCarouselFor1stTabVisible =  true;
      }, 0);
    }
  }
  
  showCarousel2(): void {
    if (this.carouselHolder2.nativeElement.clientWidth > 0 && !this.isCarouselFor1stTabVisible2) {
      setTimeout(() => {
        console.log(this.carouselHolder.nativeElement);
        this.isCarouselFor1stTabVisible2 =  true;
      }, 0);
    }
  }

Thanks-

**Comment by vitalii-andriiovskyi** [comment] 2022-04-29 15:59
@PauChan19 

`<div #carouselHolder>` doesn't have property `value`. Therefore you see in the console `undefined`

`console.log(this.carouselHolder.nativeElement.value);`
Maybe try `console.log(this.carouselHolder.nativeElement);`

**Comment by PauChan19** [comment] 2022-04-29 16:23
thanks, but the problem persist, the console is showing:
Cannot read properties of undefined (reading 'nativeElement') in the if, why?
showCarousel1(): void {
    if (this.carouselHolder.nativeElement.clientWidth > 0 && !this.isCarouselFor1stTabVisible) { 
      setTimeout(() => {
        console.log(this.carouselHolder.nativeElement);
        this.isCarouselFor1stTabVisible =  true;
      }, 0);
    }
  }

**Comment by PauChan19** [comment] 2022-04-29 16:35
there was a problem with a top ngIf, i removed it and now it works. thanks for answering

**Comment by BrachiWeiss** [comment] 2024-10-08 06:52
Hi,
I use xgx-owl-carousel-0, inside p-tabview of primeng.
Inside each panel I present a component that contains the carousel.
In the first active tab, the carousel looks and works properly.
But when moving to the second tab, the carousel looks out of order. And all the cubes are on top of each other.
In F12 I see that all the cubes get width:0px.
`<p-tabView [(activeIndex)]="activeIndex">
    <p-tabPanel>
        <ng-template pTemplate="header">
            <div class="flex align-items-center gap-2">
                
            </div>
        </ng-template>
        <ng-content select="[israelContent]"></ng-content>
    </p-tabPanel>`
I see that the 2 panels are loaded together. Although the second tab is still not visible.
Maybe it has something to do with it?
how can i fix it?
thanks
